### ISSUE TITLE
Icons not showing in some browsers

### ISSUE THREAD

**Issue by gregorybolkenstijn** [sapegin/grunt-webfont#128]
I'm on OS X 10.9 and getting mixed results. Everything works fine on Chrome and Firefox (OS X), Safari (OS X) is only showing 1 out of 4 icons, IE10, IE9 and IE8 don't show any icons. Chrome (Win7) shows same 1 icon as Safari (OS X), Firefox (Win7) shows all four. Chrome (XP) shows same 1 icon as Safari (OS X).

This is my Grunt task:

```
webfont: {
    icons: {
        src: 'images/icons/*.svg',
        dest: 'css/fonts/',
        destCss: 'css/src/partials/modules/',
        options: {
            font: 'icons',
            hashes: false,
            htmlDemo: false,
            ligatures: true,
            relativeFontPath: 'fonts/',
            stylesheet: 'scss',
            template: 'css/src/icons-font-template/_icons.css',
            types: 'eot,woff,ttf'
        }
    }
},
```

**Comment by ambienthack** [comment]
Ligature icons don't work for me in IE with grunt-webfonts 1.1.4
Looks like material icons apply two additional rules to icon (this works for me):

<pre lang="css">
.icon {
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;
  /* Support for IE. */
  font-feature-settings: 'liga';
}
</pre>
