### ISSUE TITLE
EOT not generated on Windows 7

### ISSUE THREAD

**Issue by rochejul** [sapegin/grunt-webfont#130]
Hi,

I used your great project to generate my web-fonts. However, I use the fontforge engine and I cannot generate the eot file.

If we look on the log, we can see:

``` shell
fontforge: python: can't open file ''C:\my-webfont\node_modules\grunt-webfont\tasks\engines\fontforge/../../bin/eotlitetool.py'': [Errno 22] Invalid argument
fontforge: Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
fontforge:  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
fontforge:  with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
fontforge:  Executable based on sources from 12:25 WST 25-Feb-2014-ML-TtfDb-D.
fontforge:  Library based on sources from 12:25 WST 25-Feb-2014.
fontforge:  Based on source from git with hash:4cf6fdfb64f572128c3dff4bd07d05395a0f5cf4
args:["-script","C:\\my-webfont\\node_modules\\grunt-webfont\\tasks\\engines\\fontforge\\generate.py","C:\\Users\\julien\\AppData\\Local\\Temp\\d-11424-22760-1gwilc9","./target/compiled-font","my-webfont","eot,woff,ttf,svg","--start_codepoint","0x258"]
Received JSON for fontforge:{"file": "./target/compiled-font\\my-webfont"}
```

I inspect the python script, and we can see:

``` python
if 'eot' in args.types:
    # eotlitetool.py script to generate IE7-compatible .eot fonts
    call("python '" + scriptPath + "/../../bin/eotlitetool.py' '" + fontfile + ".ttf' --output '" + fontfile + ".eot'", shell=True)
```

If I change the script like this:

``` python
if 'eot' in args.types:
    # eotlitetool.py script to generate IE7-compatible .eot fonts
    call("python \"" + scriptPath + "/../../bin/eotlitetool.py\" \"" + fontfile + ".ttf\" --output \"" + fontfile + ".eot\"", shell=True)
```

The EOT file is generated

Thank you for your feedback

Cheers

Julien Roche

**Comment by doronoded** [comment]
The reason it didn't work in my machine is: I didn't have python installed.

**Comment by penso89** [comment]
for me it's not working.
how did you do it?

**Comment by doronoded** [comment]
Install python.
Make sure the python lib is in your PATH environment variables.

Doron
בתאריך 6 ביוני 2016 09:44 PM,‏ "penso89" <notifications@github.com> כתב:

for me it's not working.
how did you do it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sapegin/grunt-webfont/issues/130#issuecomment-224050337>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADP71d3uzm1gVORcKkgN2CBBcJktEBUXks5qJGqVgaJpZM4Bmss6>
.
