### ISSUE TITLE
Yosemite Support?

### ISSUE THREAD

**Issue by CyrilKrylatov** [sapegin/grunt-webfont#189]
Hello, 

First of all, thank you for all the work you're doing here.

I wanted to know if there was any problem with grunt-webfont 0.4.8 on Yosemite.

Indeed, when I was on Mavericks everything was totally fine but since I've MaJ to Yosemite & I try to "compile" my font-icons, I have this error: 

```
$ grunt webfont
Running "webfont:icons" (webfont) task
Warning: Something went wrong when running fontforge. Probably one of your SVGs is too complicated for fontforge.

1. Try to use “node” engine instead of “fontforge”. (See “engine” option in the Readme.)

2. To find “bad” icon try to remove SVGs one by one until error disappears. Then try to simplify this SVG in Sketch, Illustrator, etc.

 Use --force to continue.

Aborted due to warnings.
```

And here is my task:

```
webfont: {
            icons: {
                src: '<%= dirs.svg.svg %>/*.svg',
                dest: '<%= src.output.webfont.fonts %>/',
                destCss: '<%= src.output.webfont.fonts %>/',
                options: {
                    templateOptions:{
                        baseClass: 'icon',
                        classPrefix: 'icon-'
                    },
                    htmlDemo: false
                }
            }
        }
```

I have already tried to remove .svg files one by one but nothing good happened.

Thank you for any updates.

**Comment by hspencer** [comment]
@sapegin I have the same issue. 

did this:

`$ brew remove fontforge`
`$ brew cleanup`
`$ brew install fontforge --with-python`
`$ npm update grunt-webfont`
`$ npm update`
`$ grunt webfont`

then,  `$ grunt webfont --verbose`:

unning "webfont:icons" (webfont) task
Verifying property webfont.icons exists in config...OK
Files: icons/add.svg, icons/alert.svg, icons/angry.svg, icons/api.svg, icons/archive.svg, icons/ask.svg, icons/attach.svg, icons/audio.svg, icons/autocomplete.svg -> fonts/pix
Verifying property webfont.icons.src exists in config...OK
Verifying property webfont.icons.dest exists in config...OK
fontforge: Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
fontforge:  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
fontforge:  with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
fontforge:  Based on sources from 18:28 CLT  1-Oct-2015-D.
fontforge:  Based on source from git with hash: 52a869492c7c91fff84a4a0a21e743078ad2712d
fontforge: Traceback (most recent call last):
fontforge:   File "/WhateverPathToProject/node_modules/grunt-webfont/tasks/engines/fontforge/generate.py", line 64, in <module>
fontforge:     glyph.addPosSub('liga', tuple(name))
fontforge: TypeError: Expected tuple of glyph names
fontforge:
Webfont did not receive a proper JSON result from Python script: SyntaxError: Unexpected end of input

Any help would be wonderfull :)

**Comment by denji** [comment]
The module is not installed py-glyph:
```bash
$ pip install glyph
```
