### ISSUE TITLE
Allow multiple stylesheet

### ISSUE THREAD

**Issue by mac2000** [sapegin/grunt-webfont#190]
something like:

```
webfont: {
    options: {
        stylesheet: ['css', 'scss']
    }
}
```

at this moment the only way i found to make it happens is generate icons two times with completely same config except needed stylesheet

**Comment by brunowego** [comment]
It would be great! +1

**Comment by cesarizu** [comment]
I've created a PR that implements this: https://github.com/sapegin/grunt-webfont/pull/349
