### ISSUE TITLE
Accessing the hash in a template

### ISSUE THREAD

**Issue by danielguillan** [sapegin/grunt-webfont#195]
I'm using a Sass mixin to include all webfonts on my site. That mixin requires a few parameters: font-family, font filename slug, font weight, font style and a cache busting string (hash).  I want to use that mixin to include my icons in the grunt-webfont template too. The only thing that I'm unable to reference in the template is the generated font file's hash. Is it available in the template?

**Comment by danielguillan** [comment]
Is it still possible to append the hash to the filename? Or somehow get it in Grunt and append it manually?

**Comment by sapegin** [comment]
@danielguillan Nope. You can do something hackish like store hash in CSS comment, then read it and rename files.

**Comment by danielguillan** [comment]
That's what I though. Thanks @sapegin !
