### ISSUE TITLE
fontforge not found on Windows

### ISSUE THREAD

**Issue by ethyde** [sapegin/grunt-webfont#208]
Hi,

When i try to launch task I have a "Warning: fontforge not found. Please install fontforge and all other requirements. Use --force to continue.". Despite numerous research, I can't find any workaround.

Anyone can help me ?

Thanks.

**Comment by eshperber** [comment]
I am having a similar issue. Tried using browser: 'node' is that not the correct way?

**Comment by stevehealy** [comment]
Same problem. No point just linking to the docs if the docs aren't explaining it clearly for everyone.
