### ISSUE TITLE
Tiny tiny icons after upgrading to 0.5.0

### ISSUE THREAD

**Issue by hacker112** [sapegin/grunt-webfont#211]
Icons became very very tiny after upgrading from 0.4.3 to 0.5.0

version 0.4.3:
https://www.dropbox.com/s/o0rf3dcuxalks8q/Sk%C3%A4rmklipp%202015-01-07%2012.51.39.png?dl=0

version 0.5.0: 
https://www.dropbox.com/s/xzl38u2xla84j34/Sk%C3%A4rmklipp%202015-01-07%2012.03.53.png?dl=0

grunt options:
```javascript
        webfont: {
            icons: {
                src: 'app/img/icons/*.svg',
                dest: 'app/css/icons',
                options: {
                    types: 'woff',
                    stylesheet: 'scss',
                    relativeFontPath: 'icons/',
                    engine: 'node'
                }
            }
        },
```

Example svg:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.4, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="32.112px" height="40px" viewBox="0 0 32.112 40" enable-background="new 0 0 32.112 40" xml:space="preserve">
<polygon points="0,0 0,40 32.112,20 "/>
</svg>
```

**Comment by sapegin** [comment]
Make your icons something like 1000px.

**Comment by hacker112** [comment]
This is obviously a bug and not a question. It worked fine before, so it is something that has broken in the last update.

**Comment by hacker112** [comment]
I now took the time time to check what happened in the code between 0.4.8 and 0.5.0.
There is an option that is called normalize (that seems to be undocumented in the Readme).

The code is changed from
```
 normalize: options.normalize !== false,
```
to
```
 normalize: options.normalize === true,
```

Which meant that in 0.4.8 normalize was the true by default and in 0.5.0 it was false by default. I see nothing about this change in the Changelog.

I also see that the all icons are rendered properly anymore, but I will create a separate issue for that.

**Comment by sapegin** [comment]
It’s undocumented because it’s available only for the Fontforge engine. If you can make output more consistent between two engines, I’ll be happy to merge your pull request. Related issue: #222.

**Comment by hacker112** [comment]
I am using the node engine (not fontforge engine) and normalize has an effect in with the node engine. Did you mean the other way around?

**Comment by sapegin** [comment]
You’re right. But as I remember it’s not the same in `node` and `fontforge` engines ;-|

I don’t use web fonts anymore and can’t spend a lot of time on the project. So if you want to help feel free to do it.

**Comment by hacker112** [comment]
Aha, I understand :-)
If I find the time I would be glad to help. Then I also need to understand why icons are getting rendered worse (or not at all) for each version and fix that ;)
https://github.com/sapegin/grunt-webfont/issues/321#issuecomment-191830688

**Comment by sapegin** [comment]
For `node` engine it’s better to start from updating [svgicons2svgfont](https://github.com/nfroidure/svgicons2svgfont): they’ve changed an API so it’s not that easy but it could fix some problems because the version used by grunt-webfont is very old.
