### ISSUE TITLE
storing json

### ISSUE THREAD

**Issue by sevenfoxes** [sapegin/grunt-webfont#218]
So my design team wants to have consistent glyphs, even if they remove them from the source at some point and add them back. i.e. "persistent  character mapping".

This is so that the rendered font can also be used in other applications (i.e. photoshop).

I've more or less got it working, except... I'm writing the codepoints to a file in the callback and sometimes... something... Just isn't ready and it writes stuff that I don't want. Here's my config:

```javascript
webfont: {
      reservoir: {
        src: [
          '<%= srcPath %>/svg/*.svg',
          '<%= srcPath %>/template.html'
        ],
        dest: '<%= distPath %>',
        destCss: '<%= distPath %>',
        options: {
          hashes:           true,
          relativeFontPath: 'fonts/',
          types:            'eot,woff,ttf,svg',
          syntax:           'bem',
          templateOptions: {
            baseClass:   'icon',
            classPrefix: '',
            mixinPrefix: 'icon_'
          },
          font:             'icons',
          stylesheet:       'scss',
          htmlDemo:         true,
          htmlDemoTemplate: '<%= srcPath %>/template.html',
          codepoints:       grunt.file.readJSON('font.json'),
          callback: function() {
              grunt.file.write('font.json', JSON.stringify(this.codepoints, undefined, 2));
          }
        }
      }
    },
```
 
I'm sure there's an easier way but I've been looking at this for about a day now and can't find where I could be going wrong. The other thing I tried was making a task that did the file writing but the context of codepoints changes

```javascript
grunt.registerTask('storesvg', function(){
    var svgToBeAdded  = grunt.config('prompt.svgAddedConfig');
    var charAssigned  = grunt.config('storesvg.iconValue');
    var existingChars = grunt.file.readJSON('glyphs.json');

    if (charAssigned !== 'autoassign') {

      existingChars[svgToBeAdded] = Number(charAssigned);
      grunt.log.write(svgToBeAdded + " assigned to " + charAssigned);

    }else{

      // existingChars[svgToBeAdded] = Number(charAssigned);
      grunt.log.write(svgToBeAdded + " assigned to new random or existing value. See font.json");

    }

    var newSvgJson = JSON.stringify(
      existingChars, undefined, 2
    );

    grunt.file.write('font.json', newSvgJson);
    grunt.task.run('webfont');
  });
```

**Comment by sapegin** [comment]
You say “sometimes” so is it works some (other) times as expected? Not sure that using `this.codepoints` is good thing.

**Comment by sevenfoxes** [comment]
Right. Sometimes the file comes out incorrectly formatted 

Well really just wanted to ensure that codepoints wasn't getting any other values. I can try with just codepoints but I think it would have the same outcome. When I get into work I'll post a bad result.

Ideally, there's just a Boolean option that says something like:

"character_map": true 

That would just drop all codepoints into a file to be used the next time it's run

**Comment by sapegin** [comment]
I think I can just add `codepoints` to `callback` function.

**Comment by sevenfoxes** [comment]
so if I just stringify codepoints, all that gets sent to the file is a string of `"icons"`. This is what I get back on a bad result:

```json
[
  "f101",
  "f102",
  "f103",
  "f14e",
  "f104",
  "f105",
  "f106",
  "f107",
  "f108",
  "f109",
  "f10a",
  "f10b",
  "f10c",
  "f10d",
  "f10e",
  "f10f",
  "f110",
  "f111",
  "f112"
]
```
Which, obviously won't work when called a second time. This is what I was expecting (and sometimes get with from `this.codepoints`:

```json
{
  "icon_add-question": 61697,
  "icon_baseball-cards": 61698,
  "icon_book-menu": 61699,
  "icon_cases": 61700,
  "icon_check-circle": 61701,
  "icon_check-no-circle": 61702,
  "icon_check": 61703,
  "icon_chevron-dn": 61704,
  "icon_chevron-lt": 61705,
  "icon_chevron-rt": 61706,
  "icon_chevron-up": 61707,
  "icon_clock": 61708,
  "icon_comment-circle": 61709,
  "icon_comment-no-circle": 61710,
  "icon_comment": 61711,
  "icon_comments-circle": 61712,
  "icon_comments-no-circle": 61713,
  "icon_comments": 61714
}
```

**Comment by sapegin** [comment]
Yeah, I can make it.

**Comment by pekala** [comment]
I'm not sure if you made any changes regarding this, but I've implemented a callback that works around problems mentioned by @sevenfoxes
```javascript
callback: function(filename, types, glyphs) {
    if (this.codepoints instanceof Array) {
        var newCodepoints = {};

        glyphs.forEach(function(name, index) {
            newCodepoints[name] = parseInt(this.codepoints[index], 16);
        }.bind(this));

        grunt.file.write('iconfont/codepoints.json', JSON.stringify(newCodepoints, null, 4));
    }
}
```

**Comment by sapegin** [comment]
There’s [codepointsFile](https://github.com/sapegin/grunt-webfont#codepointsfile) option now.
