### ISSUE TITLE
Tiny icons

### ISSUE THREAD

**Issue by ArmorDarks** [sapegin/grunt-webfont#219]
Hi

After update from `0.4.8` to `0.5.0` or `0.5.1` whenever I'm trying to generate fonts — I'm receiving extra-tiny (around 1px) icons on web-pages.

If I increase font-size — it can be seen that they are correct icons, but very small.

I've read about similar issue here #122 and I though that it was resolved. At least, at `0.4.8` all working fine.

I've done few test and discovered that issue related to small source svg icons — they are around 32x32px. If I increase their size to about 512px — they're generating as expected, with proper size.

I've tested `0.4.8` with 32x32px icons — they generating in full-scale, proper icons, on contrary to `0.5.1` and higher version.

Webfont task:

``` coffee
module.exports = ->
  @config 'webfont',
    build:
      src: 'source/icons/{,**/}*.svg'
      dest: 'build/fonts/'
      destCss: 'styles/'
      options:
        hashes: false
        styles: ''
        templateOptions:
          baseClass: 'icon'
          classPrefix: 'icon--'
        stylesheet: 'scss'
        htmlDemo: false
        engine: 'node'
```

Maybe I'm missing something?

Thanks in advance!

**Comment by sapegin** [comment]
>  If I increase their size to about 512px

Yeah, that’s what you need to do.

**Comment by ArmorDarks** [comment]
It's quite odd that from 0.5.0 svg icons doesn't upscale anymore properly. Is it intentional behavior?

The thing is, now we should always ensure that in our `svg-icon` source directory store icons of same size, otherwise we will receive unpredictable results.

From one side, it's good since forcing us to normalize all your svg-icons, but from other side it was much quicker to throw svg icon downloaded from web and working with it without bothering with svg sizes (since during rapid development stage we want to concentrate on code, not icon sizes).

So, maybe it's possible to return automatic up-scaling of svg-icons, like it was in `0.4.8`?

It sound reasonable to let node and grunt take care of sizes and normalization instead doing it manually, In the end of all, that why they were developed.


I've also wanted to ask — which exactly commit changed that behavior — so that any less then 512px svg icons now will render with improper (smaller) size?


Thanks in advance!


btw, I may be wrong, but current readme lacks any information about requirements for svg-icons, so it can be quite hard for newcomers to understand that svg-icon should be resized to 512px to work properly

**Comment by sapegin** [comment]
Actually it makes results much more predictable and makes results of both engines closer to each other.

I believe I did it here 8a0cd9b43e6b7a70e53aa539fa6863a9e093fa12. You can still use `normalize` option (though it’s not documented because it’s kind of inconsistent between engines).

There are two things that could be done (and I’ll be happy to merge pull requests for them):

1. Document some recommendations on how to prepare SVG files.

2. Make `normalize` option consistent between `node` and `fontforge` engines and document it.

**Comment by ArmorDarks** [comment]
Thanks @sapegin!

Undocumented `nomalize` option was exactly the thing which we needed.

I think that some users may prefer to tolerate slight inconsistency between engines. Should I add documentation about it into readme?

Not much I can do about 1 and 2 points, though.

Regarding point 1 — so far we can add only notation that in case `normalize` is disabled, all icons should have at least 512px height, or even better 1024px.

Though, I must say — does it really have to be larger then 512px?

**Comment by sapegin** [comment]
I’d appreciate any help with documentation. Thanks!

There were some problems with small icons and node engine but 512px should be fine I believe.
