### ISSUE TITLE
Hash check to skip doesn't work in specific case

### ISSUE THREAD

**Issue by badunk** [sapegin/grunt-webfont#224]
In the following scenario:

1. I build with a build directory "dist"
2. grunt-webfont correctly generates file and caches the hash
3. I change the build directory to "dist2"
4. I run grunt-webfont again

Result: Running grunt-webfont will not produce the file I need in dist2 dir

I think the assumption that since the hash matches, it doesn't need to generate new files is perhaps too broad.

I don't see a way, as of now, to fix this except to wipe node_modules or manually remove the hash check.

**Comment by badunk** [comment]
Actually, a slightly more realistic scenario might be:
1. grunt build
2. grunt clean
3. grunt build

Highly reproducible

**Comment by sapegin** [comment]
You can just remove any generated file. 

And of course it’s not “too broad”. Perhaps there’s a bug in hash calculation, I’ll look at it.

**Comment by badunk** [comment]
As part of the steps I mentioned above, the generated file is already deleted.  In fact, the entire output directory is wiped.  The only file that remains is hash.

I realize there's code that checks the generated code AFTER checking the hash, attempting to remedy this:

https://github.com/sapegin/grunt-webfont/blob/master/tasks/webfont.js#L131-L137

However, what happens if you have: 1) a hash 2) no files.  Since the file does not exist (https://github.com/sapegin/grunt-webfont/blob/master/tasks/webfont.js#L133), it returns false, and so it believes no regeneration is necessary.

**Comment by badunk** [comment]
Nevermind - I think I found the issue on my side.  I'll update with details

**Comment by badunk** [comment]
Hm, actually its a bit of both?

This line gets the list of generated font files.  When I've wiped my dist/ output directory, this returns with an empty array.  The next 2 lines add the demo path and the css path.

https://github.com/sapegin/grunt-webfont/blob/master/tasks/webfont.js#L128

I happen to have my css outside of my output dir, so in that case, it exists and `_.some` returns false.

If `wf.generatedFontFiles(o)` returns an empty array, I think regenerationNeeded should be true.

**Comment by badunk** [comment]
I submitted a PR https://github.com/sapegin/grunt-webfont/pull/230
