### ISSUE TITLE
[node] woff2 left anchoring icons?

### ISSUE THREAD

**Issue by Templarian** [sapegin/grunt-webfont#229]
All the other fonts appear to be generating correctly with node. Only for woff2 all the icons are anchored to the right instead of the center.

I tested all the fonts and they are all correct except for the woff2.

I use the `normalize: true` undocumented keyword to generate the 921 icons to a font.

**Comment by Templarian** [comment]
If you `bower install mid#v0.9.21-alpha` or `npm install mdi@v0.9.21-alpha`. To see this.

I'm debugging it currently to figure out if running the compression separately fixes this issue.

**Comment by sapegin** [comment]
Looks fine for me. What should I look for?

**Comment by Templarian** [comment]
All testing was done in Chrome. I'm using the icon below because it is thin and very easy to see visually, but all icons are being left aligned in WOFF2. I even tried to run the `woff2_compress font.ttf` in ssh on my server and it produced the same results.

WOFF2:
![image](https://cloud.githubusercontent.com/assets/338885/6386612/4ba24aec-bd41-11e4-817a-2163bbc337a8.png)

TTF, WOFF, EOT, SVG
![image](https://cloud.githubusercontent.com/assets/338885/6386602/22ead5f6-bd41-11e4-9a50-b45b727506ea.png)

Grunt Task:

```
src: [],
dest: 'build',
options: {
    engine: 'node',
    types: 'eot,woff2,woff,ttf,svg',
    font: 'MaterialDesignIcons',
    hashes: false,
    template: 'template.css',
    autoHint: false,
    normalize: true
}
```

SVG for the icon:

```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24">
<path d="M16,18H7V4H16M11.5,22C10.67,22 10,21.33 10,20.5C10,19.67 10.67,19 11.5,19C12.33,19 13,19.67 13,20.5C13,21.33 12.33,22 11.5,22M15.5,1H7.5C6.12,1 5,2.12 5,3.5V20.5C5,21.88 6.12,23 7.5,23H15.5C16.88,23 18,21.88 18,20.5V3.5C18,2.12 16.88,1 15.5,1Z" />
</svg>
```

I can help debug this further, but I was confused when running `woff2_compress` was producing the same results.

**Comment by Templarian** [comment]
I did some more research and found the issue...

The documentation for Google's WOFF2 is really light. There appears to be no option to tell it to keep [explicit bounding boxes](http://www.w3.org/TR/WOFF2/#glyf_table_format). I also have no idea how to submit bugs to @rsheeter who manages the project (not sure why the issue tab is disabled for a developer facing project that supports pull requests).

Horizontal Offset for the bounding box is ignored, thus all icons will left anchor (xmin-xmax = no offset). It looks like they did this because the documentation for WOFF2 says it will be calculated if it is left off.

I don't know how to fix this. The source is a little over my head. :cry:

**Comment by rsheeter** [comment]
I don't think issues was meant to be off. It is on now :)

Bounding box is supposed to be omitted only if the recalc is expected to yield the same one. From the [spec](http://dev.w3.org/webfonts/WOFF2/spec/):

```If the glyph bounding box info matches the calculated values, an encoder MUST omit the bounding box info. Otherwise, if the calculated bounding box values do not equal the glyph values encoded in a font, an encoder MUST set the corresponding bboxBitmap flag and record the original bounding box values in the bboxStream. For a composite glyph, an encoder MUST always set the corresponding bboxBitmap flag and record the original bounding box values in the bboxStream.```

It sounds like this might be going awry. Would you mind filing an issue with woff2 with a link to the ttf and the codepoint or glyph index for an icon that exhibits the problem? - preferably one where the before/after is particularly horrid.

**Comment by Templarian** [comment]
Thanks @rsheeter. I'll fill out the issue tonight after work with the examples. It looks like some online [converts](https://everythingfonts.com/woff-to-woff2) do convert with the bounding box (that's the work around I've used so far). I'll include their converted font also for comparison.

**Comment by Templarian** [comment]
I forgot to close this. Woff2 fixed it almost a month ago. Open Source is awesome like that.
