### ISSUE TITLE
Started from v0.5.0 the most of my glyphs (~90%) are not generated!

### ISSUE THREAD

**Issue by DOrlov77** [sapegin/grunt-webfont#231]
Started from v0.5.0 the most of my glyphs (~90%) are not generated correctly.
Working on Windows (7, 8, Server 2008, ...) with node engine.

I found that the resulting font size was reduced by ~25% and changelog file points to new feature:
** * Simplify source SVG files with SVGO (node engine only).**

Is there any option to disable this feature via grunt config option?
Say
```
webfont: {
    icons: {
        src: 'icons/*.svg',
        dest: 'build/fonts',
        options: {
            simplify: false
            ...
        }
    }
}
```

**Comment by sapegin** [comment]
It’s not related with SVGO and you even don’t use node engine. It’s kind of magic removal and making both engines closer to each other.

**Comment by DOrlov77** [comment]
@sapegin,
So could you confirm breaking support for Windows users?

**Comment by sapegin** [comment]
You just should not use the word “correctly” instead of “differently”. I don’t see any bug or something in you description.
