### ISSUE TITLE
Started from v0.5.0 the most of my glyphs (~90%) are not generated correctly!

### ISSUE THREAD

**Issue by DOrlov77** [sapegin/grunt-webfont#232]
Artem (@sapegin) - your answer seems to be too agressive... unreasonably. (https://github.com/sapegin/grunt-webfont/issues/231)

But **I apologize if my description was confused...**

I meant that fonts genarated using webfonts v0.5.0 are not displayed correctly while everything works just fine with previous versions. 
From that I could assume that here is the BUG that affects to CORRECT font generation :)
That is the FACT! (http://en.wikipedia.org/wiki/Fact)
Also - I just ask: is it mean breaking support for Windows users or no.

Screenshots:

![image](https://cloud.githubusercontent.com/assets/7703176/6572489/4306be02-c71b-11e4-943d-23c4d0bac52f.png)

**Comment by sapegin** [comment]
There was some magic involved that makes all icon the same size. But I don’t know how to make that magic works the same for both engines, so I disabled it by default. There are still an undocumented `normalize` options that could make generation as it was in previous versions.

But. It’s better to make sure that all your icons are of the same size (~1000px). In that case it should work fine in new version with default options.

There are two related issues: #222 and #221.

**Comment by DOrlov77** [comment]
**options.normalize = true** did the trick!

Thanks a lot Artem!
