### ISSUE TITLE
Font files generated are different for each build

### ISSUE THREAD

**Issue by iamusenix** [sapegin/grunt-webfont#234]
I recently used this grunt-webfont to generate webfont for my project. Everything worked like a charm. Only one thing confused me. 
Every time I built my svg files, the generated font files are different from the one I built before even I didn't change anything(my svg files). This made our caching strategy failed.

I looked into the font files and found there were some differences with the base64 encoding but not sure why. Anyone who ever encounter this issue or can give some help or tips? Thanks ahead.

ps: I worked on Ubuntu 14.10

**Comment by sapegin** [comment]
That’s why I added caching. That’s how Fontforge works unfortunately, it adds generation time to TTF files, and I don’t know how to disable. Node engine shouldn’t have this problem.

**Comment by gabrieledarrigo** [comment]
Node engine has the problem too.
Any hint on how to resolve the problem?
