### ISSUE TITLE
Font xxx wasn’t changed since last run

### ISSUE THREAD

**Issue by JavRok** [sapegin/grunt-webfont#241]
It's not a big issue, but it's annoying. If I'm working with a custom template for the demo page, the grunt task doesn't do anything, I get 'Font xxx wasn’t changed since last run'. So I have to edit one of the .svg files to make it update and see the changes on the .css output. It should listen to changes on those files too (template and htmlDemoTemplate).

Great module btw.

**Comment by henrahmagix** [comment]
I agree, this new feature has been really annoying me, so I always downgrade to `0.4.8`.

Can you please return the old way, perhaps under a `force` flag? May I ask the reason for not always updating?

**Comment by sapegin** [comment]
Nope. The only way is to fix bugs in the current version.

**Comment by offsky** [comment]
If you want force it to generate each time, you could use another grunt module to clean your font build folder as part of the grunt task.
