### ISSUE TITLE
Font files are not generated on windows

### ISSUE THREAD

**Issue by stanimirtt** [sapegin/grunt-webfont#244]
Hello there!

I am trying to generate icons using grunt-webfont project. CSS and HTML file are generaged but the font are not. I am on window.

![image](https://cloud.githubusercontent.com/assets/6067704/7651420/e32cc112-fb08-11e4-8317-85c8279e473a.png)

Thanks in advance!

Best Regards,
Stanimir Todorov

**Comment by brunano21** [comment]
Sure, since on Windows, grunt-webfont supports only node as engine, as explained here: https://github.com/sapegin/grunt-webfont#windows.
For that reason, you need to switch the `engine` var from font-forge (default value) to node.

**Comment by stanimirtt** [comment]
I got it. Thanks.

webfont: {
	 		icons: {
	 			src: "icons/*.svg",
	 			dest: "build/fonts",
	 			options : {
	                font: "font",
	                hashes: false,
	                engine: "node"
	            }

	 		}
	 	}
