### ISSUE TITLE
Re add option to have hashes added as part of the filename

### ISSUE THREAD

**Issue by marioestrada** [sapegin/grunt-webfont#249]
Some [proxy servers][1] have issues with cache busting using query params, this caused issues in our environment where we were seeing outdated font files being served to customers. We had to revert to the old version of the plugin.

[1]: http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

**Comment by sapegin** [comment]
I could pass a generated hash to the [callback](https://github.com/sapegin/grunt-webfont#callback). Then you could you a custom template and rename files in your gruntfile.

**Comment by marioestrada** [comment]
That would be great, I can try getting a PR ready for it too. 



- mario

**Comment by sapegin** [comment]
I would be happy to merge it, thanks!

**Comment by marioestrada** [comment]
Does this look good? https://github.com/sapegin/grunt-webfont/pull/250

**Comment by sapegin** [comment]
Yep.
