### ISSUE TITLE
Offer alternative sort orders

### ISSUE THREAD

**Issue by tandrewnichols** [sapegin/grunt-webfont#253]
Sorting icons alphabetically seems like the right default, but would you be opposed to allowing sorting by ctime or something in addition to that? The problem with alphabetical is that the content codepoints shift, so you can end up with icon classes pointing at the wrong icons (if you have a caching issue or if, like us, you have dynamically loaded css (versioned) but have to manually upload fonts for CORS reasons and didn't realize that until someone pointed out that our brand icon was suddenly the twitter icon). If they were sorted by ctime, new icons would always go at the end, and therefore couldn't mess up previous icons.

**Comment by sapegin** [comment]
You can just store codepoints to a file using [codepointsFile](https://github.com/sapegin/grunt-webfont#codepointsfile).

**Comment by tandrewnichols** [comment]
Is there an example of that? Do I have to make the file the first time or if I specify a file that doesn't exist, will it create it?

**Comment by sapegin** [comment]
No, you don’t need to create a file. grunt-webfont will create it and the will add any new codepoints.

**Comment by tandrewnichols** [comment]
Ok, we'll give it try, thanks.

**Comment by tandrewnichols** [comment]
Oh, so that's a json file. That could go in the README. I wasn't sure what extension to give it. The values in the codepoint file are like `58880`, but in the stylesheet, they're `\e600` . . . is that correct?

**Comment by tandrewnichols** [comment]
I can add some stuff to the README here shortly. Just want to understand and make sure it worked correctly.

**Comment by sapegin** [comment]
> The values in the codepoint file are like 58880, but in the stylesheet, they're \e600 . . . is that correct?

Sure, both are numbers. But the only way to store hex numbers in JSON is to convert them to strings.

**Comment by tandrewnichols** [comment]
Ok, that's the part I wasn't sure about. Thanks.
