### ISSUE TITLE
Full node WOFF2 support

### ISSUE THREAD

**Issue by nfroidure** [sapegin/grunt-webfont#254]
@sapegin  In case you missed it: https://github.com/nfroidure/ttf2woff2

I'm going to add it to gulp-iconfont, thought you'd like to do it on grunt-webfont as well.

**Comment by sapegin** [comment]
I’ll do it if I ever have time ;-)

**Comment by nfroidure** [comment]
I finally set it as an optionnal output and disabled per default since windows users seems to have some troubles with it.

**Comment by sapegin** [comment]
As always ;-)
