### ISSUE TITLE
Specific SVGs not working in Windows

### ISSUE THREAD

**Issue by SVGTest** [sapegin/grunt-webfont#256]

**Comment by SVGTest** [comment]
Can't attach the SVG files, for you to take a look.

**Comment by sapegin** [comment]
No, you can. Unless you do it and share your gruntfile I couldn’t help you.

**Comment by SVGTest** [comment]
Attached are the SVG and Grunt File.

**Comment by sapegin** [comment]
Attached to what? Upload the files somewhere (Gist for example).

**Comment by SVGTest** [comment]
Files can be found at : https://gist.github.com/SVGTest/d2f2353910edd14f5eff

**Comment by mtgibbs** [comment]
```javascript
grunt.registerTask('iconfont', ['webfont');
```

Is this line even executing properly?
