### ISSUE TITLE
Webfont not working on windows and in opera

### ISSUE THREAD

**Issue by hagenbauer** [sapegin/grunt-webfont#265]
I have successfully created a webfont with svg from Glyphicon and various others sources. They look great on Linux with Firefox and Chrome. 

But they look bad on Opera Linux/Mac and Firefox/IE Windows. 

Website www.hagen-bauer.de

Any ideas?

**Comment by sapegin** [comment]
I don’t know what is bad for you so I can’t tell. No autohinting?

**Comment by hagenbauer** [comment]
did you test it with opera or with firefox / IE in Windows
![bad-opera-linux-and ie-firefox-windows](https://cloud.githubusercontent.com/assets/3237076/8967881/3bd61900-363a-11e5-80db-5bf22b2d6d16.png)
![good-firefox-linux](https://cloud.githubusercontent.com/assets/3237076/8967882/3bd843c4-363a-11e5-8821-ed134c1016b0.png)

**Comment by sapegin** [comment]
Icons look the same. Did you to compare demo HTML pages generated by webfont?

**Comment by hagenbauer** [comment]
Ok, you are right. Icons are the same. Do you have an idea why the behave totally different. The positions are totally different.

**Comment by sapegin** [comment]
1. Check demo HTML pages generated by webfont to be sure that it’s something from webfont, not from your site’s styles.
2. Try different engine: node or fontforge.
3. Share your gruntfile and icons.

**Comment by hagenbauer** [comment]
I think I have fount the reason. I am sizing the icons with fontsize. This is working fine on my main platform Linux. Unfortunately Opera and Windows Browsers behave differently. 

I now have to find a way to increase the fonts / icons that is working.

**Comment by hagenbauer** [comment]
For me it is not understandable why the font is working on some browsers and  not working on others using the same css by just adding a fontsize. If a font is not working the same on Windows and Linux using the same Browserversion something is wrong with the generated Font and CSS.

I have not found a document how to install the node engine. Where can I find help?

**Comment by sapegin** [comment]
You don’t need to install anything except grunt-webfont itself. Just change `engine` option to `node`.

**Comment by hagenbauer** [comment]
I tried it already but I got an error so I thought something is missing

Running "webfont:icons" (webfont) task
Fatal error: Callback was already called.

 webfont: {
    icons: {
      src: '_icons/*',
      dest: 'fonts',
      destCss: '_sass',
       options: {
       stylesheet: 'scss',
       relativeFontPath: '/fonts',
       autoHint: false,
       engine : 'node',
        types: 'eot,woff2,woff,ttf,svg'
     }}},

**Comment by sapegin** [comment]
Could you send me (or upload somewhere) to artem@sapegin.ru your gruntfile and icons? It’s something that I couldn’t reproduce so far.

**Comment by hagenbauer** [comment]
you've got mail

**Comment by hagenbauer** [comment]
i have it. one of the icons was rectangular. After I resized it it seems to work  https://www.hagen-bauer.de/2015/08/grunt-web-font-probleme.html
