### ISSUE TITLE
Support for Aliases

### ISSUE THREAD

**Issue by offsky** [sapegin/grunt-webfont#272]
I am in need of aliases for some of my icons. Two classes that use the same icon.  I could include the svg twice under different names, but this would waste space. Currently, I use the "codepoints" option to force these to a specific value and then I have a custom template that hard codes the aliases to these forced codepoints. It works, but its a little messy and requires me to keep the grunt file and template in sync.  Is there a better way?

Im imagining a new options parameter in the grunt file:

```
options: {
   aliases: {
      'alert': ['warn','oops']
   }
}
````
Which would produce
```
.alert:before,.warn:before,.oops:before {
	content:"\e142";
}
```

**Comment by sapegin** [comment]
I think it’d be better to use your CSS preprocessor for that. Like `@extend` in Sass.

**Comment by offsky** [comment]
I don't use a preprocessor, so I'll keep with my original solution which works fine.  I understand wanting to avoid settings overload.  This may not be a big need for most people, but I thought I would suggest it anyway. Maybe it will get some +1s

**Comment by sapegin** [comment]
> I don't use a preprocessor.

That’s a good reason to start.

**Comment by XmlmXmlmX** [comment]
This issue was closed. Was it ever implemented?
