### ISSUE TITLE
Allow custom html file name

### ISSUE THREAD

**Issue by eddiemonge** [sapegin/grunt-webfont#277]
Be nice if there was an option to allow custom filename for the generated html file so it can be named something like `index.html`.

If https://github.com/sapegin/grunt-webfont/blob/master/tasks/webfont.js#L667 was changed to something like: 

```
		function getDemoFilePath() {
			if (!o.htmlDemo) return null;
			var name = o.demoHtmlFilename || o.fontBaseName;
			return path.join(o.destHtml, name + '.html');
		}
```

and line 78: `demoHtmlFilename: options.demoHtmlFilename,`

**Comment by eddiemonge** [comment]
related https://github.com/sapegin/grunt-webfont/issues/226

**Comment by sapegin** [comment]
Would be nice to have such pull request.

**Comment by eddiemonge** [comment]
Yeah I was being lazy. Mostly didn't want to write the test for it.
