### ISSUE TITLE
Exec change/warning

### ISSUE THREAD

**Issue by eddiemonge** [sapegin/grunt-webfont#282]
```
Running "webfont:icons" (webfont) task
exec: use child_process.execFile instead
```

**Comment by titocr** [comment]
Using the verbose option...
```
Running "webfont:icons" (webfont) task
Verifying property webfont.icons exists in config...OK
Files: svg/font-awesome/angle-left.svg -> svg-done/build/fonts
Options: fontFilename="icons-fontawesome-subset"
Verifying property webfont.icons.src exists in config...OK
New hash: 443d153344268ab06c1407eb083faced - previous hash: 021e7390cabbc2a383b0a757a01f4379
exec: use child_process.execFile instead
Fatal error: spawn ENOTDIR
```
Is it known what causes this?

**Comment by sapegin** [comment]
Which version of grunt-webfont do you use?

**Comment by eddiemonge** [comment]
```
node --version && npm --version
v5.3.0
3.3.12
```

I'm assuming grunt-webfont was 1.0.0 at the time

**Comment by titocr** [comment]
osx-yosemite, node=v5.0.0, npm 3.5.2, and I tried 1.0.2 and 1.1 of grunt-webfont.

I did see the following when switching between versions of grunt-webfont:
npm WARN deprecated exec@0.2.1: deprecated in favor of builtin child_process.execFile

**Comment by titocr** [comment]
Aha! Pilot error, at least in my case. I missed doing 'brew install ttfautohint fontforge --with-python' as specified in the readme file. After that I still get the warning to use child_process.execFile instead of exec, but then it calls fontforge and finishes with some glyphs created. Sorry for the trouble.

**Comment by eddiemonge** [comment]
```
 ● ⮀node --version && npm --version
v5.4.0
3.3.12
 ● ⮀ npm info grunt-webfont -g "version"
1.1.0
```

**Comment by eddiemonge** [comment]
Its also probably because `exec` is deprecated: https://www.npmjs.com/package/exec
