### ISSUE TITLE
Codepoints file is wiped out when there are no changes to the font

### ISSUE THREAD

**Issue by ajb** [sapegin/grunt-webfont#283]
To reproduce:

- Use this gruntfile:

```js
module.exports = function(grunt){
  grunt.initConfig({
    webfont: {
      icons: {
        src: 'icons/*.svg',
        dest: 'dist',
        options: {
          hashes: false,
          codepointsFile: 'codepoints.json'
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-webfont');
}
```

- Add an icon to the `icons/` directory and run `grunt`. A `codepoints.json` file will be generated.
- Run `grunt` again without making any changes to the icons. The contents of the `codepoints.json` file will be cleared

**Comment by mtgibbs** [comment]
Are the contents cleared or slightly modified?  My codepoints file gets regenerated, but it still contains my points.

**Comment by ajb** [comment]
Hmm... the contents are totally cleared for me.

On Fri, Nov 6, 2015 at 8:47 PM, Matt Gibbs <notifications@github.com> wrote:

> Are the contents cleared or slightly modified? My codepoints file gets
> regenerated, but it still contains my points.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sapegin/grunt-webfont/issues/283#issuecomment-154620384>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by mtgibbs** [comment]
What version of webfont-grunt do you have installed in your project?  I was playing around with codepointsFile today for my own stuff and I never lost my contents.  I'll see if I can recreate your issue this weekend and see what's up since I'm curious.

**Comment by ajb** [comment]
Hey @mtgibbs, thanks for following up on this. Here's a dummy repo: https://github.com/ajb/grunt-webfont-283 It's happening (ugh) intermittently, only every few times that I run `grunt webfont`. Just run `grunt webfont; git status` a few times and eventually you'll see `codepoints.json` show up in the diff.

Perhaps there's an issue with my environment. I can try to look into this further as well.

**Comment by mtgibbs** [comment]
Reproduces on my machine as well.  I just realized that in my workflows I'm back on ^0.5.4 so this must be something specific to 1.0.0+?  Taking a look now

**Comment by mtgibbs** [comment]
@ajb
This change seems to fix the issue.  At least in your repository.  Try it out.

https://github.com/sapegin/grunt-webfont/pull/285

**Comment by sapegin** [comment]
Please test in 1.0.1.

**Comment by ajb** [comment]
Lovely. Seems to fix it for me. Thank you both!
