### ISSUE TITLE
Update ttf2woff2 to v2 for node v4+ support

### ISSUE THREAD

**Issue by fernandopasik** [sapegin/grunt-webfont#286]
Recently there was an update in ttf2woff2 to support the new node versions.

https://github.com/nfroidure/ttf2woff2/issues/15

When installing grunt-webfont in node 5 there are some errors.

3 errors generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
Error: `make` failed with exit code: 2

**Comment by dudewad** [comment]
Yeah and I'm getting antivirus errors because of ttf2woff2 so this urgent for me (i.e. I'm dumping it from my project if I have to whitelist it on everyone's machine).
+1!

**Comment by ceehaupt** [comment]
Same here. Can't finish the installation. +1

**Comment by nfroidure** [comment]
A patch is available solving the node 4+ issue. It could also solve the AVG antivirus issue.

**Comment by sapegin** [comment]
https://github.com/sapegin/grunt-webfont/releases/tag/1.0.2
