### ISSUE TITLE
"types" option doesn't accept spaces

### ISSUE THREAD

**Issue by dudewad** [sapegin/grunt-webfont#289]
This would have been nice to know but it's undocumented. The "types" option does not accept spaces, which led me on a wild goose chase trying to figure out a number of other "bugs" on my system for why the plugin was failing.

Suggest allowing for spaces and trim them off, or at least fail with a message stating that it's reverting to default. The only reason I figure this out is because I noticed it was trying to use svg2woff2 which wasn't part of my types list.

**Comment by sapegin** [comment]
Pull request would be very nice for that.

**Comment by dudewad** [comment]
Touche! If I get some time I'll see if I can make it happen.
