### ISSUE TITLE
How can I map a specific icon to a specific character?

### ISSUE THREAD

**Issue by ashishthakur913** [sapegin/grunt-webfont#293]
Is it possible to map the icons to particular characters (unicodes?) using some naming convention?

**Comment by sapegin** [comment]
[codepoints](https://github.com/sapegin/grunt-webfont#codepoints) option should be the thing you need.

**Comment by ashishthakur913** [comment]
Thank you very much for replying.
So i had already seen this this "codepoints" option before but was unsure about its usage. So how do i use this to map the font icons to characters?
Do i set the codepoints block as
    
    codepoints: {
        filename1: unicode1,
        filename2: unicode2
    }

  with files named "filename1.svg" and "filename2.svg" in the icons folder so that the respective icon gets mapped against the mentioned unicode?

**Comment by sapegin** [comment]
It should work like this.

**Comment by ashishthakur913** [comment]
Thank you very much. One last thing.
How can I use the "codepointsFile" option?
Should that be a json file? I am unsure about its format if that is so. Can you please tell me a bit about the file extension and its format?

**Comment by ashishthakur913** [comment]
So yes we do have to make a JSON file and store the font names corresponding to ASCII character to which we want to map that font like so

{
    "bar": 97,
    "bistro": 98,
    "butcher shop": 99,
    "cakery": 100,
    "club": 101,
    "deli": 102,
    "food truck": 103,
    "kiosk": 104,
    "microbrewery": 105,
    "bakery": 106
}

 Just mentioned so that i might be useful to someone in future.
Thanks for the help.
