### ISSUE TITLE
Feature "Request": Offer JSON dump option

### ISSUE THREAD

**Issue by scottyeck** [sapegin/grunt-webfont#297]
In addition to having an HTML demo, it would be super helpful to dump the results to just a dummy JSON  object so that it can be passed into a non-HTML environment with custom templates. That way the user can pretty much do whatever they'd like!

For example:

```
webfont: {
    dist1: {
        options: {
            jsonDump: true,
            jsonDumpFilename: 'dist1-icons.json`,
            dest: 'path/to/dist1/icons',
            destCss: 'path/to/dist1/css',
            destJson: 'path/to/dist1/json'
        }
    }
}
```

The resulting file, `path/to/dist1/json/dist1-icons.json` would look like something along the lines of:

```
{
	"font": {
		"familyName": "Dist 1 Icons"
	},
	"icons": [{
		"glpyhName": "download",
		"codepoint": "\f101"
	}, {
		"glpyhName": "document",
		"codepoint": "\f102"
	}]
}
```

This would probably contain information from `fontRawSrcs` as well, likely in a similar (if not identical) format.

Happy to give this a try and submit a PR if this is a feature you're interested in the feature. :smile:

**Comment by sapegin** [comment]
Yes, do that please! :shipit:
