### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eddiemonge** [sapegin/grunt-webfont#306]
I think the MIT license can't be used for this since you using eotlitetool which has a license of "MPL 1.1/GPL 2.0/LGPL 2.1"

**Comment by sapegin** [comment]
Looks like It’s fine:

> A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.

http://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
http://programmers.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application
