### ISSUE TITLE
No need for the mixin in LESS output

### ISSUE THREAD

**Issue by braver** [sapegin/grunt-webfont#309]
In LESS a class or id is already a mixin all by itself: http://lesscss.org/features/#mixins-feature

**Comment by sapegin** [comment]
Could you send a pull request please?

**Comment by braver** [comment]
Will do!

**Comment by sapegin** [comment]
Out in 1.1.1.

**Comment by laurenskling** [comment]
It is out but it's still in the documentation?
https://github.com/sapegin/grunt-webfont#less
