### ISSUE TITLE
Class names not generating.

### ISSUE THREAD

**Issue by skindc** [sapegin/grunt-webfont#312]
I had high hopes that this grunt task was going to prevent the manual process of icomoon / fontello etc.

I am sure I have defined my grunt task as required but I have no class names being generated. The html doc generated seems to be referencing the class names that should have ben generated yet there is nothing in the scss file generated.

Do you know of a particular missing parameter or configuration that might cause this?

**Comment by scottyeck** [comment]
Would you mind providing the configuration that you're using?

**Comment by skindc** [comment]
Hi,

Firstly thanks for your prompt response.

Sorry I think I have sorted it. I provided a template css but only had the fontface declaration in there. I presumed the rest of the class declarations would be added. When I looked at your source I see the bootstrap.css template and see what was required if overriding the template.

This was a bad presumption on my part but it may be worth adding a statement to your README.md that states that when targeting your own css template that looking at the source examples may be a good idea.

Just one recommendation for really advanced configuration... and there I wull stop ;). I was about to say provide a way of passing in an Array of hash values to the css template... but you can do this with your 'customOutputs'.

Great work and thanks again. This is tool is going to really help automate my glyphs module and its flexibility means I can match any of the setting previously provided by icomoon etc.

:)

**Comment by skindc** [comment]
Highly recommended.
http://blog.skindd.co.uk/grunt-icon-font-generation/
;)
