### ISSUE TITLE
stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by JaroslavMoravec** [sapegin/grunt-webfont#319]
I use fontforge engine and building of font sometimes fails on this message:
Warning: stderr maxBuffer exceeded Use --force to continue.

I have approx. 1000 glyphs in svg. I logged in engines/fontforge data from stderr and I find out that I Have some warnings in svg files eg.

```
file:/.../zoom_out.svg:7: namespace warning : xmlns: URI &ns_svg; is not absolute
<svg  version="1.1" id="Shape_5_73_" xmlns="&ns_svg;" xmlns:xlink="&ns_xlink;" w
```

If these warnings are too much, stderr buffer exceed.

I suggest

1. show these errors in output (or only if eg. verbos: true)
2. set up size of buffer for engine exec command, or add buffer size to config eg.

`engines/fontforge.js:34`
```js
var proc = exec(args, {maxBuffer: 1024 * 500}, function(err, out, code) {
```

These warnings should be shown to user in some way and buffer should not exceed on warnings.

**Comment by sapegin** [comment]
I’ll be happy to merge pull requests for that features.
