### ISSUE TITLE
Error running fontforge when directory path contains whitespaces

### ISSUE THREAD

**Issue by lajy78** [sapegin/grunt-webfont#323]
In the file fontforge.js line 31 : 

	// Run Fontforge
	var args = [
		'fontforge',
		'-script',
		path.join(__dirname, 'fontforge/generate.py')
	].join(' ');

fontforge can not be launched when the value of the variable "__dirname" contains whitespaces.

Is it possible to fix it?

Thanks.

**Comment by sapegin** [comment]
It shouldn’t be difficult. I’ll be happy to merge a pull request with a fix.

**Comment by simonmosse** [comment]
Has anyone found a fix for this? Too many of my folder names have spaces for me to get around this by just renaming them all :( It would be very very welcome.  Thanks in advance :)

**Comment by steveh80** [comment]
This isn't too hard to fix, just change the code in line 31 to:

`'"' + path.join(__dirname, 'fontforge/generate.py') + '"'`

I don't know if this is an elegant solution to this problem, but it works on my side. I'd love to see this fixed in the next release.

**Comment by sapegin** [comment]
And already fixed, that’s why this issue was closed with a link to a pull request.

This kind of comments are quite useless: if you know how to fix something just send a pull request.
