### ISSUE TITLE
SVGO optimization should be an option

### ISSUE THREAD

**Issue by jrauschenbusch** [sapegin/grunt-webfont#325]
With the version update from v0.4.8 to v0.5.0 the function svgFilesToStreams was modified in the node engine and a new dependency to SVGO was introduced. Since v0.5.0 the function svgo.optimize() is used for every font generation process in the node engine.

This is really useful for most font generation scenarios. But in some cases this optimization destroys relevant SVG paths and attributes of the origin SVGs which results in faulty web fonts.

Hence there should be an Option to enable/disable the SVGO optimizer.

Relates to #231

**Comment by sapegin** [comment]
Feel free to submit a pull request.

**Comment by jrauschenbusch** [comment]
Great! A new release v1.3.0 would be great.
