### ISSUE TITLE
Is there a way to generate a variables.less/scss like icomoon does?

### ISSUE THREAD

**Issue by Deklin** [sapegin/grunt-webfont#348]
Is there a way to generate a variables.less/scss like icomoon does?

We use this for places where we need the code for the font, and prefer to use a variable vs hardcoding it.

Is this possible?

**Comment by fry2k** [comment]
This would be great. Right now I have a grunt task which parse the generated css file and writes a *.scss file.
I use variables and also an array variant cause of a mixin.
for example:
`$bde-icon-load: "\f112";`
`$bde-icon-log: "\f113";`
`$bde-icons: (
	load: "\f112",
	log: "\f113"
);`

**Comment by ediblecode** [comment]
You can use a custom [template](https://github.com/sapegin/grunt-webfont#template) to generate a custom output, with variables etc. See an example below where you can generate a SASS map of your icons:

*Gruntfile.js*
```JavaScript
webfont: {
  icons: {
    template: "icons.tmpl.scss"
  }
}
```

*icons.tmpl.scss* - see https://lodash.com/docs/4.16.2#template
```JavaScript
// Map of icon name to codepoint
$icons: (
<% _.forEach(glyphs, function(glyph, index) { %>
  ${ glyph }: "${ codepoints[index] }",<% }); %>
);

@mixin icon($icon) {
  $code: map-get($icons, $icon);
  content: unquote('\'\\#{ $code }\'');
}

// Generate BEM style selector for each icon
.icon {
  font-family: "${ fontFamilyName }";

  <% _.forEach(glyphs, function(glyph, index) { %>
  &--${ glyph }:before {
    @include icon(${ glyph });
  }
  <% }); %>
}
```

**Comment by fry2k** [comment]
thanks @ediblecode this solved my request :+1:

**Comment by jasedwards** [comment]
Is there a way to do one for scss and less?  It appears you can generate both types of files at once but can only provide one template.

**Comment by scottyeck** [comment]
@jasedwards You should be able to use the `customOutputs` option for this.

**Comment by Deklin** [comment]
I was able to do this as well w/ customOuptuts. Working very well.

**Comment by jasedwards** [comment]
ah ok.  so that replaces my templates and dest from options right?  Previously I was only doing less but have a need for both now.
