### ISSUE TITLE
Project status, ownership, etc.

### ISSUE THREAD

**Issue by sapegin** [sapegin/grunt-webfont#355]
grunt-webfont still has quite a lot of uses (35 000 downloads per month) but I have no time and will to maintain it. And I don’t use Grunt or icon fonts for a long time. I don’t even check new issues here anymore.

I’ll be happy to add more people as contributors or transfer ownership if anyone is interested.

[Related issue](https://github.com/gruntjs/grunt/issues/1567) at Grunt repo.

**Comment by alampros** [comment]
🙋‍♂️ I know it's been a while since you posted this, but I'd be happy to help!

I've been using this in a few projects for a long time and would love to see it continued.

**Comment by sapegin** [comment]
@alampros Hi, thank your your offer! I can easily give you push rights to the repo and publish rights to the npm package ;-)

**Comment by alampros** [comment]
@sapegin sounds good! How do we proceed?

**Comment by sapegin** [comment]
@alampros The first is easy (done), for the second I need your npm user name and then I’ll google how to do it ;-)

**Comment by alampros** [comment]
@sapegin well that's an easy one too - same as my github (alampros). :)

**Comment by sapegin** [comment]
It wasn’t difficult ;-)

```
❯ npm owner ls grunt-webfont
alampros <alampros@gmail.com>
sapegin <artem@sapegin.ru>
```

I used to use [a script](https://github.com/sapegin/dotfiles/blob/master/bin/release) to make new releases but I suggest you to [set up semantic-release](http://blog.sapegin.me/all/semantic-release) to simplify the release process. But it’s all up to you — whatever you prefer ;-)
