### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Norreman** [sapegin/grunt-webfont#363]
There were several bugfixes and features added in march. Will there be a release for that?

The font-path-variables would be a great feature to have in a new release.

**Comment by lotz** [comment]
I would love to have the `fontPathVariables` option as well! Please push a new release. 👍

**Comment by lotz** [comment]
Looks like @alampros is the new owner. Hopefully this feature will be released on NPM soon in a new version. 😄

**Comment by alampros** [comment]
👋 
I was going to attempt to get `semantic-release` up and running for the next release, but I will try to cut a release to the `beta` `dist-tag` on npm later today so we can at least get these out there for now.

**Comment by lotz** [comment]
Thanks!

**Comment by alampros** [comment]
Just published [1.7.0](https://github.com/sapegin/grunt-webfont/releases/tag/1.7.0) to the `beta` dist-tag.
