### ISSUE TITLE
classname suffix

### ISSUE THREAD

**Issue by joguerre** [sapegin/grunt-webfont#372]
Is there an option available to add a classname 'suffix' to class, example:
```
templateOptions: {
    baseClass: 'mIcon',
    classPrefix: 'mIcon.j-',
    classSuffix: '.jr' //suffix, please verify if possible
}
```
=
// rendered sample showing '.jr' suffix:
`.mIcon.j-MenuButton.jr:before {}`

**Comment by alampros** [comment]
No there is not, but you can achieve this using the [template](https://github.com/sapegin/grunt-webfont#template) configuration param.
