### ISSUE TITLE
why is generated iconfont so big?

### ISSUE THREAD

**Issue by chenxiaochun** [sapegin/grunt-webfont#373]
I have many svg files, but a few of them are very large after they are generated. 

![image](https://user-images.githubusercontent.com/1744713/32998851-7132ea68-cdd9-11e7-9371-489a30daf4a5.png)

* This is true in both Mac and Linux systems
* node version: `8.4.0`
* zip package: [iconfont.zip](https://github.com/sapegin/grunt-webfont/files/1486246/iconfont.zip)
* svg file source code:

```html
<svg viewBox="0 0 14 2" xmlns="http://www.w3.org/2000/svg"><rect width="14" height="2" rx="1" fill="#666" fill-rule="evenodd"/></svg>
```

**Comment by alampros** [comment]
Your viewbox should be normalized to 512x512px
