### ISSUE TITLE
Sass-variables for icons

### ISSUE THREAD

**Issue by chrisheinzelmann** [sapegin/grunt-webfont#73]
i use grunt-webfont with sass and create a file with variables for each icon by hand - something like this:

``` sass
$icon-close: "\f105";
$icon-single-arrow: "\f116";
```

so i can use them like this:

``` sass
content: $icon-close;
```

It would be cool if those variables are generated automatically.

**Comment by brunowego** [comment]
+1

**Comment by artursopelnik** [comment]
+1
