### ISSUE TITLE
Enable options for custom font height (font.em) and ascent and descent values.

### ISSUE THREAD

**Issue by brettlaforge** [sapegin/grunt-webfont#99]
It would be nice to be able to specify the font height and ascent and descent values in the grunt configuration. This would make fonts of different sizes available. Specifically i have a bunch of svgs already sized to 1000px and would like to create a font with an em value to match.

It would also open up the use of the following projects which have adapted fontawesome, iconic, and entypo to a common height and width.

https://github.com/fontello/awesome-uni.font
https://github.com/fontello/iconic-uni.font
https://github.com/fontello/entypo

**Comment by nfroidure** [comment]
The node engine now also support the ascent option https://github.com/nfroidure/svgicons2svgfont/commit/b619af0d71d61b4ff6326e49dc9054ff1835b4e6
